name: "identity"
backend: "oneflow"
max_batch_size: 16
input [
  {
    name: "INPUT_0"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]
output [
  {
    name: "OUTPUT_0"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]

instance_group [
  { 
    count: 1
    kind: KIND_CPU
  }
]

dynamic_batching {
  max_queue_delay_microseconds: 5000000
}

parameters {
  key: "xrt"
  value: {
    string_value: "openvino"
  }
}
